# Change these first
owner: bryan-herrera-dev # Your GitHub organization or username, where this repository lives
repo: status-for-my-web-pages # The name of this repository

sites:
  - name: Bryan Herrera Portfolio
    url: https://bryan-herrera.netlify.app/
    assignees:
      - Bryan-Herrera-DEV
  - name: GithubProfile whith Charts
    url: https://bryan-herrera-dev.github.io/Github-Profile-View-With-Charts
    assignees:
      - Bryan-Herrera-DEV

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-for-my-web-pages
  name: Live Status Page
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Live Status Page
      href: /
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
  #configs para el diseño de la pagina
  theme: night
  introTitle: "**Live Status Page** es una página de monitorización y estado del tiempo de actividad de código abierto, impulsada completamente por GitHub."
  logoUrl: https://raw.githubusercontent.com/Bryan-Herrera-DEV/status-for-my-web-pages/0859be7a4cb87798b0c52d063c1b5eb108019f0c/assets/LiveStatusPage.svg
  favicon: https://raw.githubusercontent.com/Bryan-Herrera-DEV/status-for-my-web-pages/master/assets/LiveStatusPage.png
 
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
